# Ciphers Configuration file

# Encryption schemes ordered by preference.
cipherPreferences:
    - STD
    - DET
    - HOM
    - FPE
    - SE
    - OPE

# Optional. Encryption schemes supported by the secure database system to be used. Requires the specification of the
# properties preserved by each scheme.
supportedCiphers:
  - name: STD
    properties:
  - name: DET
    properties:
      - EQUALITY
  - name: OPE
    properties:
      - EQUALITY
      - ORDER